/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author avumi
 */
public class StudentSignUp extends javax.swing.JFrame {

    /**
     * Creates new form StudentSignUp
     */
    public StudentSignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFirstName = new javax.swing.JTextField();
        jLastName = new javax.swing.JTextField();
        jPassword = new javax.swing.JTextField();
        jGradeComboBox = new javax.swing.JComboBox<>();
        jConfirmPassword = new javax.swing.JPasswordField();
        jBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 500, 40));
        getContentPane().add(jLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 530, 40));

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 530, 40));

        jGradeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "000", "00", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));
        jGradeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGradeComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jGradeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 140, 40));
        getContentPane().add(jConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 400, 40));

        jBackground.setIcon(new javax.swing.ImageIcon("C:\\Users\\avumi\\OneDrive\\Documents\\NetBeansProjects\\PATAvumileG12\\StudentSignUpSized.jpg")); // NOI18N
        getContentPane().add(jBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jGradeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGradeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jGradeComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackground;
    private javax.swing.JPasswordField jConfirmPassword;
    private javax.swing.JTextField jFirstName;
    private javax.swing.JComboBox<String> jGradeComboBox;
    private javax.swing.JTextField jLastName;
    private javax.swing.JTextField jPassword;
    // End of variables declaration//GEN-END:variables
}
