/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author avumi
 */
public class WelcomePage extends javax.swing.JFrame {

    /**
     * Creates new form WelcomePage
     */
    public WelcomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAdminSignUp = new javax.swing.JButton();
        jAdminLogin = new javax.swing.JButton();
        jParentSignUp = new javax.swing.JButton();
        jParentLogin = new javax.swing.JButton();
        jStudentSignUp = new javax.swing.JButton();
        jStudentLogin = new javax.swing.JButton();
        jWelcomePic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jAdminSignUp.setText("SIGN UP");
        jAdminSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdminSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(jAdminSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 200, 30));

        jAdminLogin.setText("LOGIN");
        jAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAdminLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 200, 30));

        jParentSignUp.setText("SIGN UP");
        getContentPane().add(jParentSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 200, 30));

        jParentLogin.setText("LOGIN");
        getContentPane().add(jParentLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 200, 30));

        jStudentSignUp.setText("SIGN UP");
        jStudentSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStudentSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(jStudentSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 170, 30));

        jStudentLogin.setText("LOGIN");
        jStudentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStudentLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jStudentLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 170, 30));

        jWelcomePic.setIcon(new javax.swing.ImageIcon("C:\\Users\\avumi\\OneDrive\\Documents\\NetBeansProjects\\PATAvumileG12\\Welcomepage resized.png")); // NOI18N
        getContentPane().add(jWelcomePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdminLoginActionPerformed
        // TODO add your handling code here:
         AdminLogin choose = new AdminLogin();
        this.hide();
        choose.show();
    }//GEN-LAST:event_jAdminLoginActionPerformed

    private void jAdminSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAdminSignUpActionPerformed
        // TODO add your handling code here:
         AdminSignUp choose = new AdminSignUp();
        this.hide();
        choose.show();
       
    }//GEN-LAST:event_jAdminSignUpActionPerformed

    private void jStudentSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStudentSignUpActionPerformed
        // TODO add your handling code here:
         StudentSignUp choose = new StudentSignUp ();
        this.hide();
        choose.show();
    }//GEN-LAST:event_jStudentSignUpActionPerformed

    private void jStudentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStudentLoginActionPerformed
        // TODO add your handling code here:
         StudentLogin choose = new StudentLogin ();
        this.hide();
        choose.show();
    }//GEN-LAST:event_jStudentLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WelcomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAdminLogin;
    private javax.swing.JButton jAdminSignUp;
    private javax.swing.JButton jParentLogin;
    private javax.swing.JButton jParentSignUp;
    private javax.swing.JButton jStudentLogin;
    private javax.swing.JButton jStudentSignUp;
    private javax.swing.JLabel jWelcomePic;
    // End of variables declaration//GEN-END:variables
}
